### ISSUE TITLE
бустер

### ISSUE THREAD

**Issue by DiOnFire** [sekkej/sekkej#1]
а бустер такой непон нюхай бебру

**Comment by sekkej** [comment]
😾😼😼😼🦾💀В ЭТОМ СЛОВЕ😰⚧️ТРАНСГЕНДЕР?🧗🔥 я типичный комментатор ffm😎➡: ‼‼🚬 ля вы крисы🤡❓Всему🥶🥶.АНА😍☝️ чел сверху сосал 👇😎ХОЧУ🧛🔥🔥БОМБИТТО🤬🦣ТЕБЯ🦣
